"""Add year field with default to IsuzuMotors

Revision ID: 12db6bab0819
Revises: 4159cc76c2d4
Create Date: 2025-06-30 12:02:24.982199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12db6bab0819'
down_revision: Union[str, Sequence[str], None] = '4159cc76c2d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('isuzumotors', sa.Column('year', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('isuzumotors', 'year')
    # ### end Alembic commands ###
