"""initial schema

Revision ID: 4159cc76c2d4
Revises: 
Create Date: 2025-06-28 14:31:22.160650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4159cc76c2d4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('isuzumotors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('chassis_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('start_number', sa.Integer(), nullable=False),
    sa.Column('end_number', sa.Integer(), nullable=False),
    sa.Column('remarks', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('isuzumotors')
    # ### end Alembic commands ###
