"""added more data tables of different companies

Revision ID: e2adb5771256
Revises: 12db6bab0819
Create Date: 2025-06-30 12:55:45.670927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'e2adb5771256'
down_revision: Union[str, Sequence[str], None] = '12db6bab0819'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daihatsumotorcorporation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('chassis_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('start_number', sa.Integer(), nullable=False),
    sa.Column('end_number', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('remarks', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hinomotorscorporation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('chassis_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('start_number', sa.Integer(), nullable=False),
    sa.Column('end_number', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('remarks', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hondamotor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('chassis_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('start_number', sa.Integer(), nullable=False),
    sa.Column('end_number', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('remarks', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kawasakimotorscorporation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('chassis_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('start_number', sa.Integer(), nullable=False),
    sa.Column('end_number', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('remarks', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mazdamotorcorporation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('chassis_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('start_number', sa.Integer(), nullable=False),
    sa.Column('end_number', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('remarks', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mitsubishifusotruckandbuscorporation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('chassis_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('start_number', sa.Integer(), nullable=False),
    sa.Column('end_number', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('remarks', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mitsubishimotors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('chassis_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('start_number', sa.Integer(), nullable=False),
    sa.Column('end_number', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('remarks', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nissanmotor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('chassis_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('start_number', sa.Integer(), nullable=False),
    sa.Column('end_number', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('remarks', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subarucorporation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('chassis_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('start_number', sa.Integer(), nullable=False),
    sa.Column('end_number', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('remarks', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('suzukimotorcorporation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('chassis_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('start_number', sa.Integer(), nullable=False),
    sa.Column('end_number', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('remarks', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('toyotamotorcorporation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('chassis_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('start_number', sa.Integer(), nullable=False),
    sa.Column('end_number', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('remarks', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('udtrucks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('chassis_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('start_number', sa.Integer(), nullable=False),
    sa.Column('end_number', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('remarks', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('yamahamotor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('chassis_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('start_number', sa.Integer(), nullable=False),
    sa.Column('end_number', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('remarks', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('isuzumotors', 'year',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('isuzumotors', 'year',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_table('yamahamotor')
    op.drop_table('udtrucks')
    op.drop_table('toyotamotorcorporation')
    op.drop_table('suzukimotorcorporation')
    op.drop_table('subarucorporation')
    op.drop_table('nissanmotor')
    op.drop_table('mitsubishimotors')
    op.drop_table('mitsubishifusotruckandbuscorporation')
    op.drop_table('mazdamotorcorporation')
    op.drop_table('kawasakimotorscorporation')
    op.drop_table('hondamotor')
    op.drop_table('hinomotorscorporation')
    op.drop_table('daihatsumotorcorporation')
    # ### end Alembic commands ###
